---
- name: install kibana
  hosts: kibana
  become: yes
  vars:
    elastic_httphost: 192.168.17.10:9200
  tasks:

  - name: install package kibana
    apt:
      deb: "https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.9-amd64.deb"

  - name: copy config kibana
    template:
      src: /home/ivanozhigov/github/diplom/ansible/kibana.conf.yml
      dest: /etc/kibana/kibana.yml

  - name: daemon_reload
    systemd:
      daemon_reload: true

  - name:  restart kibana
    service:
      name: kibana
      state: restarted
      enabled: yes
