---
- name: install zabbix
  hosts: zabbix
  become: true
  vars:
    pass_zabbixdb: zabbix

  tasks:
    - name: download zabbix
      shell: wget https://repo.zabbix.com/zabbix/7.2/release/ubuntu/pool/main/z/zabbix-release/zabbix-release_latest+ubuntu24.04_all.deb
      args:
        chdir: /tmp

    - name: install zabbix
      shell: dpkg -i zabbix-release_latest+ubuntu24.04_all.deb
      args:
        chdir: /tmp

    - name: update
      apt:
        update_cache: yes

    - name: install package zabbix
      apt:
        name:
          - apache2
          - postgresql
          - postgresql-contrib
          - zabbix-server-pgsql
          - zabbix-frontend-php
          - php8.3-pgsql
          - zabbix-apache-conf
          - zabbix-sql-scripts
          - zabbix-agent
        state: present
      become: yes
    - name: create user PostgreSQL for zabbix
      ansible.builtin.expect:
        command: sudo -u postgres createuser --pwprompt zabbix
        responses:
          (?i).*(Enter password for new role)(.*):
           - '{{ pass_zabbixdb }}'
          (?i).*(Enter it again)(.*):
           - '{{ pass_zabbixdb }}'

    - name: create db PostgreSQL for zabbix
      shell: >
        sudo -u postgres createdb -O zabbix zabbix

    - name: import
      shell:
        zcat /usr/share/zabbix/sql-scripts/postgresql/server.sql.gz | sudo -u zabbix psql zabbix

    - name: custom DBPassword
      lineinfile:
        path: /etc/zabbix/zabbix_server.conf
        regexp: '^DBPassword='
        line: 'DBPassword=zabbix'
    - name: restart zabbix
      service:
        name: "{{ item }}"
        state: restarted
        enabled: yes

      loop:
        - zabbix-server
        - zabbix-agent
        - apache2
